import { FunctionComponent, PropsWithChildren } from 'react';
import Head from 'next/head';
import styled from '@emotion/styled';
import Header from '../header';

const BaseLayout: FunctionComponent<PropsWithChildren> = ({ children }) => {
  return (
    <>
      <Head>
        <title>XMS-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainWrapper>{children}</MainWrapper>
    </>
  );
};

export default BaseLayout;

const MainWrapper = styled.main`
  padding: 1rem;
`;
